apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: k8s-user-60
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30102
  type: NodePort