apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-1
  namespace: k8s-user-60
  labels:
    app: web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      name: web
      namespace: k8s-user-60
      labels:
        app: web-server
        env: python
    spec:
      containers:
        - name: nginx
          image: gohiei/simple-web:0.1
          imagePullPolicy: IfNotPresent

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
  namespace: k8s-user-60
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    # for old k8s cluster:
    # apiVersion: extensions/v1beta1
    apiVersion: apps/v1
    kind: Deployment
    name: web-deployment-1
  targetCPUUtilizationPercentage: 50